// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Munin.proto

package com.monitoring.munin_node;

public final class protos {
  private protos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface PluginsOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {
    
    // repeated .muninproto.Plugins.Plugin plugin = 1;
    java.util.List<com.monitoring.munin_node.protos.Plugins.Plugin> 
        getPluginList();
    com.monitoring.munin_node.protos.Plugins.Plugin getPlugin(int index);
    int getPluginCount();
  }
  public static final class Plugins extends
      com.google.protobuf.GeneratedMessageLite
      implements PluginsOrBuilder {
    // Use Plugins.newBuilder() to construct.
    private Plugins(Builder builder) {
      super(builder);
    }
    private Plugins(boolean noInit) {}
    
    private static final Plugins defaultInstance;
    public static Plugins getDefaultInstance() {
      return defaultInstance;
    }
    
    public Plugins getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public interface PluginOrBuilder
        extends com.google.protobuf.MessageLiteOrBuilder {
      
      // required string name = 1;
      boolean hasName();
      String getName();
      
      // required string config = 2;
      boolean hasConfig();
      String getConfig();
      
      // required string update = 3;
      boolean hasUpdate();
      String getUpdate();
    }
    public static final class Plugin extends
        com.google.protobuf.GeneratedMessageLite
        implements PluginOrBuilder {
      // Use Plugin.newBuilder() to construct.
      private Plugin(Builder builder) {
        super(builder);
      }
      private Plugin(boolean noInit) {}
      
      private static final Plugin defaultInstance;
      public static Plugin getDefaultInstance() {
        return defaultInstance;
      }
      
      public Plugin getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      private int bitField0_;
      // required string name = 1;
      public static final int NAME_FIELD_NUMBER = 1;
      private java.lang.Object name_;
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getName() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (com.google.protobuf.Internal.isValidUtf8(bs)) {
            name_ = s;
          }
          return s;
        }
      }
      private com.google.protobuf.ByteString getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8((String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      
      // required string config = 2;
      public static final int CONFIG_FIELD_NUMBER = 2;
      private java.lang.Object config_;
      public boolean hasConfig() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getConfig() {
        java.lang.Object ref = config_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (com.google.protobuf.Internal.isValidUtf8(bs)) {
            config_ = s;
          }
          return s;
        }
      }
      private com.google.protobuf.ByteString getConfigBytes() {
        java.lang.Object ref = config_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8((String) ref);
          config_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      
      // required string update = 3;
      public static final int UPDATE_FIELD_NUMBER = 3;
      private java.lang.Object update_;
      public boolean hasUpdate() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getUpdate() {
        java.lang.Object ref = update_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (com.google.protobuf.Internal.isValidUtf8(bs)) {
            update_ = s;
          }
          return s;
        }
      }
      private com.google.protobuf.ByteString getUpdateBytes() {
        java.lang.Object ref = update_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8((String) ref);
          update_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      
      private void initFields() {
        name_ = "";
        config_ = "";
        update_ = "";
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;
        
        if (!hasName()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasConfig()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasUpdate()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getNameBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, getConfigBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeBytes(3, getUpdateBytes());
        }
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getNameBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, getConfigBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(3, getUpdateBytes());
        }
        memoizedSerializedSize = size;
        return size;
      }
      
      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }
      
      public static com.monitoring.munin_node.protos.Plugins.Plugin parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static com.monitoring.munin_node.protos.Plugins.Plugin parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static com.monitoring.munin_node.protos.Plugins.Plugin parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static com.monitoring.munin_node.protos.Plugins.Plugin parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static com.monitoring.munin_node.protos.Plugins.Plugin parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static com.monitoring.munin_node.protos.Plugins.Plugin parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static com.monitoring.munin_node.protos.Plugins.Plugin parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static com.monitoring.munin_node.protos.Plugins.Plugin parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static com.monitoring.munin_node.protos.Plugins.Plugin parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static com.monitoring.munin_node.protos.Plugins.Plugin parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.monitoring.munin_node.protos.Plugins.Plugin prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageLite.Builder<
            com.monitoring.munin_node.protos.Plugins.Plugin, Builder>
          implements com.monitoring.munin_node.protos.Plugins.PluginOrBuilder {
        // Construct using com.monitoring.munin_node.protos.Plugins.Plugin.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }
        
        private void maybeForceBuilderInitialization() {
        }
        private static Builder create() {
          return new Builder();
        }
        
        public Builder clear() {
          super.clear();
          name_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          config_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          update_ = "";
          bitField0_ = (bitField0_ & ~0x00000004);
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }
        
        public com.monitoring.munin_node.protos.Plugins.Plugin getDefaultInstanceForType() {
          return com.monitoring.munin_node.protos.Plugins.Plugin.getDefaultInstance();
        }
        
        public com.monitoring.munin_node.protos.Plugins.Plugin build() {
          com.monitoring.munin_node.protos.Plugins.Plugin result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }
        
        private com.monitoring.munin_node.protos.Plugins.Plugin buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          com.monitoring.munin_node.protos.Plugins.Plugin result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return result;
        }
        
        public com.monitoring.munin_node.protos.Plugins.Plugin buildPartial() {
          com.monitoring.munin_node.protos.Plugins.Plugin result = new com.monitoring.munin_node.protos.Plugins.Plugin(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.name_ = name_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.config_ = config_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.update_ = update_;
          result.bitField0_ = to_bitField0_;
          return result;
        }
        
        public Builder mergeFrom(com.monitoring.munin_node.protos.Plugins.Plugin other) {
          if (other == com.monitoring.munin_node.protos.Plugins.Plugin.getDefaultInstance()) return this;
          if (other.hasName()) {
            setName(other.getName());
          }
          if (other.hasConfig()) {
            setConfig(other.getConfig());
          }
          if (other.hasUpdate()) {
            setUpdate(other.getUpdate());
          }
          return this;
        }
        
        public final boolean isInitialized() {
          if (!hasName()) {
            
            return false;
          }
          if (!hasConfig()) {
            
            return false;
          }
          if (!hasUpdate()) {
            
            return false;
          }
          return true;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                
                return this;
              default: {
                if (!parseUnknownField(input, extensionRegistry, tag)) {
                  
                  return this;
                }
                break;
              }
              case 10: {
                bitField0_ |= 0x00000001;
                name_ = input.readBytes();
                break;
              }
              case 18: {
                bitField0_ |= 0x00000002;
                config_ = input.readBytes();
                break;
              }
              case 26: {
                bitField0_ |= 0x00000004;
                update_ = input.readBytes();
                break;
              }
            }
          }
        }
        
        private int bitField0_;
        
        // required string name = 1;
        private java.lang.Object name_ = "";
        public boolean hasName() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        public String getName() {
          java.lang.Object ref = name_;
          if (!(ref instanceof String)) {
            String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
            name_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        public Builder setName(String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          name_ = value;
          
          return this;
        }
        public Builder clearName() {
          bitField0_ = (bitField0_ & ~0x00000001);
          name_ = getDefaultInstance().getName();
          
          return this;
        }
        void setName(com.google.protobuf.ByteString value) {
          bitField0_ |= 0x00000001;
          name_ = value;
          
        }
        
        // required string config = 2;
        private java.lang.Object config_ = "";
        public boolean hasConfig() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        public String getConfig() {
          java.lang.Object ref = config_;
          if (!(ref instanceof String)) {
            String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
            config_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        public Builder setConfig(String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          config_ = value;
          
          return this;
        }
        public Builder clearConfig() {
          bitField0_ = (bitField0_ & ~0x00000002);
          config_ = getDefaultInstance().getConfig();
          
          return this;
        }
        void setConfig(com.google.protobuf.ByteString value) {
          bitField0_ |= 0x00000002;
          config_ = value;
          
        }
        
        // required string update = 3;
        private java.lang.Object update_ = "";
        public boolean hasUpdate() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        public String getUpdate() {
          java.lang.Object ref = update_;
          if (!(ref instanceof String)) {
            String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
            update_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        public Builder setUpdate(String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          update_ = value;
          
          return this;
        }
        public Builder clearUpdate() {
          bitField0_ = (bitField0_ & ~0x00000004);
          update_ = getDefaultInstance().getUpdate();
          
          return this;
        }
        void setUpdate(com.google.protobuf.ByteString value) {
          bitField0_ |= 0x00000004;
          update_ = value;
          
        }
        
        // @@protoc_insertion_point(builder_scope:muninproto.Plugins.Plugin)
      }
      
      static {
        defaultInstance = new Plugin(true);
        defaultInstance.initFields();
      }
      
      // @@protoc_insertion_point(class_scope:muninproto.Plugins.Plugin)
    }
    
    // repeated .muninproto.Plugins.Plugin plugin = 1;
    public static final int PLUGIN_FIELD_NUMBER = 1;
    private java.util.List<com.monitoring.munin_node.protos.Plugins.Plugin> plugin_;
    public java.util.List<com.monitoring.munin_node.protos.Plugins.Plugin> getPluginList() {
      return plugin_;
    }
    public java.util.List<? extends com.monitoring.munin_node.protos.Plugins.PluginOrBuilder> 
        getPluginOrBuilderList() {
      return plugin_;
    }
    public int getPluginCount() {
      return plugin_.size();
    }
    public com.monitoring.munin_node.protos.Plugins.Plugin getPlugin(int index) {
      return plugin_.get(index);
    }
    public com.monitoring.munin_node.protos.Plugins.PluginOrBuilder getPluginOrBuilder(
        int index) {
      return plugin_.get(index);
    }
    
    private void initFields() {
      plugin_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      for (int i = 0; i < getPluginCount(); i++) {
        if (!getPlugin(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < plugin_.size(); i++) {
        output.writeMessage(1, plugin_.get(i));
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < plugin_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, plugin_.get(i));
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.monitoring.munin_node.protos.Plugins parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.monitoring.munin_node.protos.Plugins parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.monitoring.munin_node.protos.Plugins parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.monitoring.munin_node.protos.Plugins parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.monitoring.munin_node.protos.Plugins parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.monitoring.munin_node.protos.Plugins parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.monitoring.munin_node.protos.Plugins parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.monitoring.munin_node.protos.Plugins parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.monitoring.munin_node.protos.Plugins parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.monitoring.munin_node.protos.Plugins parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.monitoring.munin_node.protos.Plugins prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.monitoring.munin_node.protos.Plugins, Builder>
        implements com.monitoring.munin_node.protos.PluginsOrBuilder {
      // Construct using com.monitoring.munin_node.protos.Plugins.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        plugin_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.monitoring.munin_node.protos.Plugins getDefaultInstanceForType() {
        return com.monitoring.munin_node.protos.Plugins.getDefaultInstance();
      }
      
      public com.monitoring.munin_node.protos.Plugins build() {
        com.monitoring.munin_node.protos.Plugins result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.monitoring.munin_node.protos.Plugins buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.monitoring.munin_node.protos.Plugins result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.monitoring.munin_node.protos.Plugins buildPartial() {
        com.monitoring.munin_node.protos.Plugins result = new com.monitoring.munin_node.protos.Plugins(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          plugin_ = java.util.Collections.unmodifiableList(plugin_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.plugin_ = plugin_;
        return result;
      }
      
      public Builder mergeFrom(com.monitoring.munin_node.protos.Plugins other) {
        if (other == com.monitoring.munin_node.protos.Plugins.getDefaultInstance()) return this;
        if (!other.plugin_.isEmpty()) {
          if (plugin_.isEmpty()) {
            plugin_ = other.plugin_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensurePluginIsMutable();
            plugin_.addAll(other.plugin_);
          }
          
        }
        return this;
      }
      
      public final boolean isInitialized() {
        for (int i = 0; i < getPluginCount(); i++) {
          if (!getPlugin(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                
                return this;
              }
              break;
            }
            case 10: {
              com.monitoring.munin_node.protos.Plugins.Plugin.Builder subBuilder = com.monitoring.munin_node.protos.Plugins.Plugin.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addPlugin(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .muninproto.Plugins.Plugin plugin = 1;
      private java.util.List<com.monitoring.munin_node.protos.Plugins.Plugin> plugin_ =
        java.util.Collections.emptyList();
      private void ensurePluginIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          plugin_ = new java.util.ArrayList<com.monitoring.munin_node.protos.Plugins.Plugin>(plugin_);
          bitField0_ |= 0x00000001;
         }
      }
      
      public java.util.List<com.monitoring.munin_node.protos.Plugins.Plugin> getPluginList() {
        return java.util.Collections.unmodifiableList(plugin_);
      }
      public int getPluginCount() {
        return plugin_.size();
      }
      public com.monitoring.munin_node.protos.Plugins.Plugin getPlugin(int index) {
        return plugin_.get(index);
      }
      public Builder setPlugin(
          int index, com.monitoring.munin_node.protos.Plugins.Plugin value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePluginIsMutable();
        plugin_.set(index, value);
        
        return this;
      }
      public Builder setPlugin(
          int index, com.monitoring.munin_node.protos.Plugins.Plugin.Builder builderForValue) {
        ensurePluginIsMutable();
        plugin_.set(index, builderForValue.build());
        
        return this;
      }
      public Builder addPlugin(com.monitoring.munin_node.protos.Plugins.Plugin value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePluginIsMutable();
        plugin_.add(value);
        
        return this;
      }
      public Builder addPlugin(
          int index, com.monitoring.munin_node.protos.Plugins.Plugin value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePluginIsMutable();
        plugin_.add(index, value);
        
        return this;
      }
      public Builder addPlugin(
          com.monitoring.munin_node.protos.Plugins.Plugin.Builder builderForValue) {
        ensurePluginIsMutable();
        plugin_.add(builderForValue.build());
        
        return this;
      }
      public Builder addPlugin(
          int index, com.monitoring.munin_node.protos.Plugins.Plugin.Builder builderForValue) {
        ensurePluginIsMutable();
        plugin_.add(index, builderForValue.build());
        
        return this;
      }
      public Builder addAllPlugin(
          java.lang.Iterable<? extends com.monitoring.munin_node.protos.Plugins.Plugin> values) {
        ensurePluginIsMutable();
        super.addAll(values, plugin_);
        
        return this;
      }
      public Builder clearPlugin() {
        plugin_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        
        return this;
      }
      public Builder removePlugin(int index) {
        ensurePluginIsMutable();
        plugin_.remove(index);
        
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:muninproto.Plugins)
    }
    
    static {
      defaultInstance = new Plugins(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:muninproto.Plugins)
  }
  
  
  static {
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
