# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='Munin.proto',
  package='muninproto',
  serialized_pb='\n\x0bMunin.proto\x12\nmuninproto\"m\n\x07Plugins\x12*\n\x06plugin\x18\x01 \x03(\x0b\x32\x1a.muninproto.Plugins.Plugin\x1a\x36\n\x06Plugin\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x0e\n\x06\x63onfig\x18\x02 \x02(\t\x12\x0e\n\x06update\x18\x03 \x02(\tB%\n\x19\x63om.monitoring.munin_nodeB\x06protosH\x03')




_PLUGINS_PLUGIN = descriptor.Descriptor(
  name='Plugin',
  full_name='muninproto.Plugins.Plugin',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='name', full_name='muninproto.Plugins.Plugin.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='config', full_name='muninproto.Plugins.Plugin.config', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='update', full_name='muninproto.Plugins.Plugin.update', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=82,
  serialized_end=136,
)

_PLUGINS = descriptor.Descriptor(
  name='Plugins',
  full_name='muninproto.Plugins',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='plugin', full_name='muninproto.Plugins.plugin', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_PLUGINS_PLUGIN, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=27,
  serialized_end=136,
)

_PLUGINS_PLUGIN.containing_type = _PLUGINS;
_PLUGINS.fields_by_name['plugin'].message_type = _PLUGINS_PLUGIN
DESCRIPTOR.message_types_by_name['Plugins'] = _PLUGINS

class Plugins(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class Plugin(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _PLUGINS_PLUGIN
    
    # @@protoc_insertion_point(class_scope:muninproto.Plugins.Plugin)
  DESCRIPTOR = _PLUGINS
  
  # @@protoc_insertion_point(class_scope:muninproto.Plugins)

# @@protoc_insertion_point(module_scope)
